### ISSUE TITLE
Doesn't work for web.xml error-page

### ISSUE THREAD

**Issue by jonbrock** [qaware/x-forwarded-filter#5]
Hi,

When an error causes the webapp to use the page defined in the error-page tag in web.xml, this filter doesn't try to handle the error dispatch.

I believe this is due to the code in OncePerRequestFilter.java:
```
    /**
     * Whether to filter error dispatches such as when the servlet container
     * processes and error mapped in {@code web.xml}. The default return value
     * is "true", which means the filter will not be invoked in case of an error
     * dispatch.
     *
     * @since 3.2
     */
    protected boolean shouldNotFilterErrorDispatch() {
        return true;
    }
```

Changing that to false fixes the issue for me.
Another option is to override shouldNotFilterErrorDispatch in ForwardedHeaderFilter.java if the desire is to preserve OncePerRequestFilter (which appears to come from Spring).

**Comment by Michael-Frank** [comment]
So your proposal is, that ForwardedHeaderFilter processing should also (per default) happen during error dispatch. Correct?

**Comment by Michael-Frank** [comment]
closed due to inactivity
